### ISSUE TITLE
Each time you type '/huds reload', the size of the file increases indefinitely.

### ISSUE THREAD

**Issue by madebygood** [Ehhthan/HappyHud-Issues#1]
1) type '/huds reload'

2) look at your 'plugins\HappyHUD\pack'

3) size is increased

**Comment by Ehhthan** [comment]
I cannot reproduce this issue. What version of the plugin and minecraft are you using? Are you changing anything before you do the reload?

**Comment by madebygood** [comment]
It was a temporary phenomenon. thank you
-problem solving-
