### ISSUE TITLE
textures dont work at 1.20+

### ISSUE THREAD

**Issue by Lorikaz** [Ehhthan/HappyHud-Issues#100]
i have premade pack for happyhud and im using it on 1.18.2. but its not rendering correctly in 1.20

i have 2 shaders for removing background of scoreboard
1 for 1.20+
and other one for 1.18+

i downgraded the api version of happyhud so it can work with 1.18.2 it doesnt give me any error. it works fine i guess.

i tried older versions of happyhud but its not compatible with latest version of premadepack.

before upgrading the happyhud:
![Screenshot_20240204-165856.png](https://github.com/Ehhthan/HappyHud-Issues/assets/94652683/67e20091-df69-488a-8612-f7f46ada2e59)

after upgrading it and changing pack version to 1.20:
![Screenshot_20240204-212447.png](https://github.com/Ehhthan/HappyHud-Issues/assets/94652683/666ae97e-e455-41c8-8c51-ebc7c5dabd14)

idk how to fix the darkend textures of the hud and the positioning of it

**Comment by Ehhthan** [comment]
1.18 is not supported.

**Comment by Lorikaz** [comment]
well, how am i gone use it properly than?
if you made a plugin. yoou have to made it compatible with all versions. Ik mojang changed the shader render types  after 1.19

**Comment by Ehhthan** [comment]
I state clearly on the plugin page that the plugin supports only 1.19 and 1.20. This is further reinforced by the fact that the api version is 1.19. When you edit the jar, you cannot expect support.

**Comment by Lorikaz** [comment]
> I state clearly on the plugin page that the plugin supports only 1.19 and 1.20. This is further reinforced by the fact that the api version is 1.19. When you edit the jar, you cannot expect support.

yeeeah, makes sense
