### ISSUE TITLE
Option to hide default exp number via shader

### ISSUE THREAD

**Issue by Boy0000** [Ehhthan/HappyHud-Issues#11]
using https://github.com/McTsts/mc-core-shaders#move-xp-number you can add an option to move it or just hide it by setting alpha to 0

**Comment by Ehhthan** [comment]
Additional shader options:

- Hide health
- Hide side bar

**Comment by Boy0000** [comment]
This would be great yeah

**Comment by Ehhthan** [comment]
You can now manually edit the shader file in 0.2.0. This should allow you to combine shaders.
