### ISSUE TITLE
Support for original color codes format

### ISSUE THREAD

**Issue by JpegIsMe** [Ehhthan/HappyHud-Issues#14]
If possible, we'd like to have the ability to use the normal color code format (&6, §6, etc) since we're having placeholder issues because of it, and it is what most plugins use and is generally the most popular format by far. Thanks for considering.

**Comment by Ehhthan** [comment]
That format is legacy and will not be used.

**Comment by Ehhthan** [comment]
Added a conversion for legacy formatting in 0.1.5-SNAPSHOT
