### ISSUE TITLE
Fix Position

### ISSUE THREAD

**Issue by Lerphie** [Ehhthan/HappyHud-Issues#16]
I want to suggest such an idea from another plugin. The idea is to "Fix Position"
Plugin: https://www.spigotmc.org/resources/addon-betterhud-now-without-any-limitations.84180/
![image](https://user-images.githubusercontent.com/66962762/189566902-d60d36d1-734d-4118-9a8f-4714832c2b99.png)
![image](https://user-images.githubusercontent.com/66962762/189566913-063ff46c-42ef-4246-bf73-57e2cc2a1d53.png)

**Comment by Ehhthan** [comment]
Added in 0.2.0 under alignment.
