### ISSUE TITLE
TownyAdvance actionbar messages 

### ISSUE THREAD

**Issue by Truongvv10** [Ehhthan/HappyHud-Issues#22]
Hi, I'm writing in regard of Action Bar listeners not working for towny eventhough this is what it sais on the plugin page.
![image](https://user-images.githubusercontent.com/67742370/193457963-6a7704fe-9d18-4edf-8a90-8c62b33b97d2.png)

What's not working is notifications sent as players move between plots using **`Towny Advanced`**.

When I go from town plot to winderness plot (unclaimed land), I see is this:
![image](https://user-images.githubusercontent.com/67742370/193458187-feb5775b-8d6f-4cf4-8017-baa57564f4d7.png)

But you're supposes to see.
![image](https://user-images.githubusercontent.com/67742370/193458228-b8dc1c6d-cd51-4b8b-acca-1a30b4cc1c55.png)

I have tested this with HappyHUD and without HappyHUD. Could we add compatibility to TowyAdvanced? Players don't see any information about plots anymore when moving between chunks.

**Comment by haroldrc** [comment]
same problem, also gives the problem with other plugins. pls fix it
 @Ehhthan

**Comment by Ehhthan** [comment]
Fixed in 0.2.0.
