### ISSUE TITLE
Please add chinese characters to actionbar

### ISSUE THREAD

**Issue by LXY010327** [Ehhthan/HappyHud-Issues#26]
[default-fonts.zip](https://github.com/Ehhthan/HappyHud-Issues/files/9960768/default-fonts.zip)

Please add it to the plugin, really thx

**Comment by LXY010327** [comment]
if add those directly, when i send actionbar message, the problem [https://github.com/Ehhthan/HappyHud-Issues/issues/2](url) will happen.
![1](https://user-images.githubusercontent.com/62154109/200572130-2874af1d-d5dc-47b2-b068-f2b4188e49bd.png)
![2](https://user-images.githubusercontent.com/62154109/200572140-d20800f8-9bad-4907-a8c6-40cb93e55ef3.png)
![3](https://user-images.githubusercontent.com/62154109/200572150-fb5a369f-a3cd-401a-81df-92249ed85c7c.png)
![4](https://user-images.githubusercontent.com/62154109/200572464-5b301436-224f-4723-a4b0-6625f149e19f.png)
HappyHUD-0.1.6-SNAPSHOT

**Comment by Ehhthan** [comment]
Fixed in 0.2.0.
