### ISSUE TITLE
UI appears dark in 1.19

### ISSUE THREAD

**Issue by robinbogoslovsky** [Ehhthan/HappyHud-Issues#28]
Running on HappyHUD-0.1.6-SNAPSHOT.jar
compatibility-mode: false was tested
compatibility-mode: true was tested

Process of reloading: /happyhud reload -> upload in pack -> F3 T -> disconnect -> reconnect = doesn't work
1.18 displays the right colors
1.19 displays the dark colors

I am 99% sure I am doing everything right but it never works.

Contact me in PM Lordinouille#0110 to test this out if needed
![2022-11-19_20 00 57](https://user-images.githubusercontent.com/93200084/202875188-424c4948-2589-47ae-93ec-241355999cff.png)

**Comment by robinbogoslovsky** [comment]
Fully regenerated the happyhud file with comp mode at false and have
![2022-11-19_23 22 32](https://user-images.githubusercontent.com/93200084/202875404-afe07e42-7aa3-4123-ab81-0d3820f7e918.png)
 this:
Still dark
I don't really see how it could be an issue on my side

**Comment by Ehhthan** [comment]
Fixed in 0.2.0.
