### ISSUE TITLE
HUD is not shown for certain players

### ISSUE THREAD

**Issue by Complex1t** [Ehhthan/HappyHud-Issues#29]
I am overwriting health in icons.png and using HappyHUD to draw custom health hud. It is all configured correctly. However, it seems that for certain users, the icons.png override works but the health hud does not display, so as a result they don’t have any health display.  This is rare (4/100? cases) - but it is there for those and it is game breaking for them. 2 of those 4 people reached out and they did everything they could (clear out server resource packs, use only the default Minecraft resource pack, use stock Minecraft launcher, make a new game profile, reinstall Minecraft), and the issue persists. I tried removing/readding/resetting the layouts using `/happyhud layout` with no success. The only commonality between these 2 people that I found is that they are on macOS (but I’m not sure why that would cause any issues… I tested on macOS and it worked fine for me).

I originally posted this on Discord on November 15, but I thought I'd also post it here if it helps you keep track.

Purpur 1.19.2. ProtocolLib build 600. No viaversion/viabackwards.

**Comment by Ehhthan** [comment]
I am completely stumped at what could possibly be causing this. If anyone else has additional information that would be helpful.

**Comment by iPymad** [comment]
> 

Someone, on discord, said that this could be solved "add .fsh to modify the color". I don't even understand what does that mean but might help ...

**Comment by Joshinn-io** [comment]
In my experience with core shaders @Ehhthan it comes down to the type of chip in it. Integrated Intel, Old stuff especially.

**Comment by Complex1t** [comment]
The mac I tested on was on Apple Silicon, M1. I don't have access to an Intel mac, so I can't test it myself.

If it helps, here's a client log of one of the players affected by this issue: https://mclo.gs/2AzDGOn

I don't know if they are on Intel or Apple Silicon. Haven't seem them for a while.

**Comment by Complex1t** [comment]
> In my experience with core shaders @Ehhthan it comes down to the type of chip in it. Integrated Intel, Old stuff especially.

You may be right. I just dug up an old i5-4590, HD Graphics 4600 system and I don't have any HUD.

Here's the client log: https://mclo.gs/6Vbzlte

**Comment by haroldrc** [comment]
same problem

**Comment by Ehhthan** [comment]
https://www.intel.com/content/www/us/en/support/articles/000005524/graphics.html

These are the specifications for OpenGL and Intel processors w/ dedicated graphics. I can specify the glsl version in the shader so will work on trying to adapt it to support lower versions.

**Comment by haroldrc** [comment]
can i fix it somehow?

**Comment by Ehhthan** [comment]
@Complex1t 
Can you update your graphics drivers and report back please: https://www.intel.com/content/www/us/en/support/detect.html

**Comment by Complex1t** [comment]
Intel doesn't let me update the drivers myself from their site due to the computer being from an OEM.

"The driver being installed is not validated for this computer. Please obtain the appropriate driver from the computer manufacturer."

Well, the latest driver Dell provides is 20.19.15.4531 which I already tested with, and that's 6 years old. I'd imagine this would be the case for the majority of users as well... even if Intel pushes driver updates, manufacturers simply won't.

**Comment by Complex1t** [comment]
I did manage to bypass the lock by downloading the drivers, disabling wifi, going into safe mode, uninstalling the OEM drivers with DDU, installing 15.40.48.5171 downloaded straight from Intel, and restarting. It made no difference - HUD is still gone.

Not to mention, even if it worked, that's a steep process with a lot to go wrong. Not everyone would have the technical abilities to do it.

**Comment by Ehhthan** [comment]
> I did manage to bypass the lock by downloading the drivers, disabling wifi, going into safe mode, uninstalling the OEM drivers with DDU, installing 15.40.48.5171 downloaded straight from Intel, and restarting. It made no difference - HUD is still gone.
> 
> Not to mention, even if it worked, that's a steep process with a lot to go wrong. Not everyone would have the technical abilities to do it.

Yeah obviously would not be a great solution even if it did work. Don't know if there is much hope for a fix for this since shaders are so essential. Both reports are from systems using HD 4600 graphics and researching online I can see some other people having issues with that version. Even though it says it supports the correct version of OpenGL. If you could try setting the shader version manually in the rendertype_text.vsh file on the first line to 110 that could possibly work.

**Comment by Ehhthan** [comment]
@Complex1t Is there a way I can add you on discord so I can send you builds to test?

**Comment by Complex1t** [comment]
> > I did manage to bypass the lock by downloading the drivers, disabling wifi, going into safe mode, uninstalling the OEM drivers with DDU, installing 15.40.48.5171 downloaded straight from Intel, and restarting. It made no difference - HUD is still gone.
> > Not to mention, even if it worked, that's a steep process with a lot to go wrong. Not everyone would have the technical abilities to do it.
> 
> Yeah obviously would not be a great solution even if it did work. Don't know if there is much hope for a fix for this since shaders are so essential. Both reports are from systems using HD 4600 graphics and researching online I can see some other people having issues with that version. Even though it says it supports the correct version of OpenGL. If you could try setting the shader version manually in the rendertype_text.vsh file on the first line to 110 that could possibly work.

I tried setting the shader version to 110 with no success.



> @Complex1t Is there a way I can add you on discord so I can send you builds to test?

Yes, Complex#1530

**Comment by Ehhthan** [comment]
@Complex1t I've added you.

**Comment by Ehhthan** [comment]
Good news, @Complex1t and I have figured out the issue. This will be officially fixed when I release 0.2.0 in the next coming days.

**Comment by haroldrc** [comment]
did you really understand how to fix it? @Ehhthan (i love you)

**Comment by Ehhthan** [comment]
Fixed in 0.2.0.
