### ISSUE TITLE
PLAYER PERFORMANCE ISSUE

### ISSUE THREAD

**Issue by iamnoksio** [Ehhthan/HappyHud-Issues#34]
There's a performance issue when plugin display multiple font with the placeholder information in

**Comment by Ehhthan** [comment]
Please leave more information about this. Timings report, configs, and any logs.

**Comment by iamnoksio** [comment]
dont need timings, find it and FIX IT

**Comment by Ehhthan** [comment]
> dont need timings, find it and FIX IT

dont need fix, find logs and POST THEM

**Comment by iamnoksio** [comment]
basic skid L
