### ISSUE TITLE
ItemsAdder contents path error.

### ISSUE THREAD

**Issue by YKDZ** [Ehhthan/HappyHud-Issues#35]
In ItemsAdder 3.3, they change the file structure and here is their [introduction](https://itemsadder.devs.beer/3-3-vs-3-2).
So for HappyHud, the correct path should be:
built-pack/minecraft --> ItemsAdder/contents/minecraft/resourcepack/
built-pack/happyhud --> ItemsAdder/contents/happyhud/resourcepack/
And we can not do this only use 1 path selector in copy-resource-pack feature.
Splitting the two files like this may solve this problem:
https://mcpaste.com/f22963b331152e15097e07ed90e6bcbc

**Comment by Ehhthan** [comment]
Plan to keep old version and potentially add a version that can split the files. ItemsAdder is keeping compatibility with the old version so there's not a huge incentive to push quickly.

**Comment by Ehhthan** [comment]
Added support in version 0.3.1-SNAPSHOT.
