### ISSUE TITLE
SHADERS CAUSE FPS DROPS AND ERRORS

### ISSUE THREAD

**Issue by Phoenix-99** [Ehhthan/HappyHud-Issues#37]
the new version of HappyHUD PremadePack [Vanilla & MMOCore] 1.1.2 has a problem with shaders file, it cause fps drops
and minecraft looks like this
![image](https://user-images.githubusercontent.com/63762282/215977631-33cc8c31-5b0d-4883-8c98-6999458b33eb.png)
the fps drops is fixed when you delete shaders files but all the Action Bars breaks and it disappear

**Comment by Ehhthan** [comment]
This addon is not affiliated with HappyHud. If you are having issues with that pack please contact the author.
