### ISSUE TITLE
/happyhud reload causes server crash.

### ISSUE THREAD

**Issue by Jeck** [Ehhthan/HappyHud-Issues#38]
I encountered this issue on the prior build (0.3.0-SNAPSHOT) and the current (0.3.1-SNAPSHOT). In both cases I was using the default config; something about copying files itself fails in a crash.

Please find attached the relevant crash information:
[crash.txt](https://github.com/Ehhthan/HappyHud-Issues/files/10672431/crash.txt)

**Comment by Jeck** [comment]
I think this relates to file permissions; I moved the server to a different drive and had no issues. Back on the old drive, issues. Etc. 

The old drive is exFAT formatted for compatibility reasons but that's a terrible filesystem and I regret everything. Probably that's the cause of the problems though.

My suggestion is, if you can, to wrap the java.nio.file calls inside CopyFileVisitor in a try/catch block so it doesn't bring the whole server down when things go wrong. It also happened during the copy built-pack stuff as well, afaik.

**Comment by Ehhthan** [comment]
I'm gonna try to catch the the IOExceptions to hopefully fix this.
