### ISSUE TITLE
Possible incompatibility with Triton

### ISSUE THREAD

**Issue by DeonHarwnart** [Ehhthan/HappyHud-Issues#39]
After testing, When installing Triton and Happy Hud together I notice that the server freeze to the point that it crashes later.
The freeze started after a player join. After removing Triton, everything came back to normal and the server stop freezing.

Triton plugin on Spigot: https://www.spigotmc.org/resources/triton-translate-your-server.30331/
(translate your server into multiple languages)

The repeating error before the server stopped is included here: https://pastebin.com/5ahYbGud

Mention:
- The action bar also stop working completely. (No text shown)

**Comment by Ehhthan** [comment]
Have you attempted to completely disable triton dealing with action bars. Due to the way happyhud formats huds, another plugin editing text will not work. Report back if the first option works.

**Comment by y2why** [comment]
> После тестирования при совместной установке Triton и Happy Hud я заметил, что сервер зависает до такой степени, что позже он падает. Заморозка началась после присоединения игрока. После удаления Тритона все пришло в норму и сервер перестал зависать.
> 
> Плагин Triton на Spigot: https://www.spigotmc.org/resources/triton-translate-your-server.30331/ (переведите свой сервер на несколько языков)
> 
> Повторяющаяся ошибка перед остановкой сервера включена сюда: https://pastebin.com/5ahYbGud
> 
> Упомянуть:
> 
> * Панель действий также полностью перестает работать. (Текст не показан)

To avoid conflicts between the Triton and HappyHud plugins, disable in the Triton configuration - action-bar: false in the config. Helped me.
