### ISSUE TITLE
Make missing texture/asset/elements etc not fully disable the plugin

### ISSUE THREAD

**Issue by Boy0000** [Ehhthan/HappyHud-Issues#4]
Right now the entire plugin is disabled when this happens, and a full restart is needed.
Ideally it would simply disable those specific layers, so that you could fix it and do a simple reload
![image](https://user-images.githubusercontent.com/62521371/186867740-474a1ca4-6584-4a91-aa9a-6338fb04c513.png)

**Comment by Ehhthan** [comment]
Added in 1.0.4-RELEASE
