### ISSUE TITLE
Bar reversal function display problem

### ISSUE THREAD

**Issue by LingYuersgit** [Ehhthan/HappyHud-Issues#41]
If I use the reversal function of the blood bar, although the direction of image reduction is reversed, but the entire blood bar is still left-aligned and the reduction will continue to indent to the left, reversing the direction of reduction should be right-aligned to reduce the left.

**Comment by LingYuersgit** [comment]
I hope you can solve this little problem soon

**Comment by Ehhthan** [comment]
I believe this is intended behavior.

**Comment by Ehhthan** [comment]
Tracking this issue in #42 .
