### ISSUE TITLE
Fill part of vertical-orientation-hud is not correct

### ISSUE THREAD

**Issue by CyberStorm3868** [Ehhthan/HappyHud-Issues#42]
Like picture below
![image](https://user-images.githubusercontent.com/78129732/220272422-e713538b-feee-4333-a3f2-4aeee331465f.png)
Red one is reversed: false
Blue one is reversed: true
When reversed is set to false, the hud-fill-part position is not correct.
![image](https://user-images.githubusercontent.com/78129732/220272954-96a414a8-8c6e-4db7-8d34-b91aaae5ae10.png)
![image](https://user-images.githubusercontent.com/78129732/220272994-d56c335a-a26c-4511-a7e2-f3511f80695f.png)

**Comment by Ehhthan** [comment]
Fixed in 0.3.2-SNAPSHOT.
