### ISSUE TITLE
"$" text in action bar causes all HUD to disappear

### ISSUE THREAD

**Issue by Complex1t** [Ehhthan/HappyHud-Issues#43]
All HUD disappears if an action bar with the character "$" is sent to a player.

Have a HUD active, and use this command to send yourself an action bar title that says "$"
/title playername actionbar {"text":"$"}

Purpur 1.19.3, HappyHUD 0.3.1

**Comment by Ehhthan** [comment]
Can confirm issue when updating versions 0.3.0 -> 0.3.1.

**Comment by Ehhthan** [comment]
Fixed in 0.3.3-SNAPSHOT.
