### ISSUE TITLE
HUD disappears briefly due to legacy formatting codes sent to the action bar

### ISSUE THREAD

**Issue by Complex1t** [Ehhthan/HappyHud-Issues#44]
Some plugins send messages to the action bar using legacy formatting codes, and the action bar passthrough in HappyHUD can't deal with it properly.

If a plugin sends an action bar message with legacy formatting codes, the whole HUD disappears for a second and this error occurs:
`[01:46:23] [Server thread/ERROR]: [HappyHUD] Unhandled exception number 64 occurred in onPacketSending(PacketEvent) for HappyHUD
com.ehhthan.libraries.kyori.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.adventure.kyori.net) for more information.
	§&§x§&<aqua>§&</aqua><aqua>§&§c§&</aqua><dark_blue>§&</dark_blue><red>§&</red><dark_purple>Click with the edit tool away from an armor stand to select an editing mode first!
	                             ^^`

If you need reference/example plugin, this message was sent by the ArmorStandEditor-Reborn plugin.

HappyHUD 0.3.4, Purpur 1.19.3

**Comment by Ehhthan** [comment]
HappyHud already translates legacy color codes to the new format. It appears that the message ArmorStandEditor is malformed.

**Comment by Ehhthan** [comment]
Cannot reproduce this on Paper 1.19.3 and HappyHud-0.3.4-SNAPSHOT. I also used the ArmorStandEditor-Reborn 1.19.4-40.2 to test and the message came through fine. I would suggest regenerating your locale file for that plugin.
