### ISSUE TITLE
Compatibility with itemsaader.

### ISSUE THREAD

**Issue by Surtryyds** [Ehhthan/HappyHud-Issues#45]
I hope that HappyHud can be compatible with itesadder, so that the text effect function of itemsadder can be used and the hud can also run normally.

**Comment by Ehhthan** [comment]
Will not be possible without cooperation from LoneDev.

**Comment by Surtryyds** [comment]
I have asked the author of itemsadder to add compatibility to happyhud in issues, and I hope you can reach a cooperation to make these two plugins compatible.

**Comment by Surtryyds** [comment]
> Owner

I have asked the author of itemsadder to add compatibility to happyhud in issues, and I hope you can reach a cooperation to make these two plugins compatible.
