### ISSUE TITLE
How Can I fix that error

### ISSUE THREAD

**Issue by tyristana** [Ehhthan/HappyHud-Issues#46]
`
> [00:40:05 WARN]: [HappyHud] Task #198263241 for HappyHUD v0.3.4-SNAPSHOT generated an exception
> java.lang.NullPointerException: Cannot invoke "com.ehhthan.happyhud.api.hud.active.element.ActiveElement.getConditionResult()" because "<local3>" is null
>         at com.ehhthan.happyhud.api.hud.active.element.ActivePopup.build(ActivePopup.java:74) ~[HappyHUD-0.3.4-SNAPSHOT.jar:?]
>         at com.ehhthan.happyhud.api.hud.active.element.ActivePopup$TimedActiveElement.lambda$new$0(ActivePopup.java:96) ~[HappyHUD-0.3.4-SNAPSHOT.jar:?]
>         at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1632]
>         at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.2.jar:git-Purpur-1632]
>         at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1559) ~[purpur-1.18.2.jar:git-Purpur-1632]
>         at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1632]
>         at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[purpur-1.18.2.jar:git-Purpur-1632]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
>         at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
`

**Comment by Ehhthan** [comment]
Misconfigured conditions.
