### ISSUE TITLE
Happy Hud action bar can't render font images.

### ISSUE THREAD

**Issue by Rastart21** [Ehhthan/HappyHud-Issues#49]
https://i.imgur.com/KPFnzdq.png
This is the action bar when happy hud installed.

https://i.imgur.com/GnrOytc.png
This is when happy hud isn't installed.

**Comment by Ehhthan** [comment]
You need to register your font images in whatever font you have selected for the actionbar pop up

**Comment by Rastart21** [comment]
And how do i do that ? is if different like doing it on hud ? can you give me an example

**Comment by YKDZ** [comment]
Tried to add it but fail. :( Also need an example.
