### ISSUE TITLE
Reloading huds sometimes doesnt update active huds

### ISSUE THREAD

**Issue by Boy0000** [Ehhthan/HappyHud-Issues#5]
Seems sometimes a relog is necessary for it to resend the hud correctly after reloading via commands.
Guess it doesnt update the hud correctly from old->new after reload. Not sure what the criteria for this is but

**Comment by Ehhthan** [comment]
Plugin should force update active layouts after reload.

**Comment by Boy0000** [comment]
Does majority of the time yeah, though sometimes it seems to not.
After reloading the RP it is all mushed up. Dont have any steps to really reproduce it consistently but yeah

**Comment by Ehhthan** [comment]
Should be fixed in 0.1.3-SNAPSHOT. Please confirm.

**Comment by Ehhthan** [comment]
I think this is still an issue.

**Comment by Boy0000** [comment]
It is still an issue yeah, as of 0.1.4-SNAPSHOT

**Comment by S2GN** [comment]
Layouts break completely or won't update when changing layout positions. 0.1.6-SNAPSHOT
(Purpur 1.19.2)

**Comment by Ehhthan** [comment]
Fixed in 0.2.0.
