### ISSUE TITLE
It isn't exactly compatible with CustomNameplates

### ISSUE THREAD

**Issue by LoganTheOverlord** [Ehhthan/HappyHud-Issues#51]
Basically, CN overrides HappyHud's Bossbar, but not actionbar. Which makes HH unusable with CN. I would love option to reposition bar to bar 2, for example, but found no such option. Also found no option for listener priroty.

Is compatibility possible here, or shall I... drop the idea?

Many thanks!

**Comment by Ehhthan** [comment]
Happyhud currently only uses the action bar.

**Comment by LoganTheOverlord** [comment]
Wait, so... the HUD in top of screen is not bossbar? That is confusing, as the HUD content on top is literally Bossbar. I mean, I bought a package that uses BossBar (MyHUD).
Can you pull the same ability to filter for bossbar?
