### ISSUE TITLE
[Feature Request] Ignore Bedrock (Geyser) Players

### ISSUE THREAD

**Issue by Complex1t** [Ehhthan/HappyHud-Issues#53]
Hello, since the concept of HappyHUD is impossible on Bedrock, would it be possible for HappyHUD to completely ignore Bedrock players connecting via Geyser? Currently, any action bars sent to Bedrock players are not sent as HappyHUD tries to process them.

**Comment by totallynotsoul** [comment]
Don't bedrock servers do this?

**Comment by Complex1t** [comment]
HappyHUD has nothing to do with Bedrock servers.
