### ISSUE TITLE
Block Text

### ISSUE THREAD

**Issue by stfj123** [Ehhthan/HappyHud-Issues#54]
Hello, I am a Chinese player
When I put the resource package of haapyhud on the client, my text will turn into squares

https://pic1.imgdb.cn/item/646eef8bf024cca1731981c6.png

I probably know it's caused by the shaders folder in happyhud. Because if I delete it, it's gone. But I cannot completely solve the problem, and even after deleting my interface, there is no default content.

I hope to get help

**Comment by Ehhthan** [comment]
Something is wrong with your configuration. Try a fresh install.
