### ISSUE TITLE
Difficulties with offset...

### ISSUE THREAD

**Issue by distribate** [Ehhthan/HappyHud-Issues#56]
Hi!!

When the interface is upscaled, all text elements are shifted from the bottom... What am I doing wrong?

1 screenshot: interface 2x size
2 screenshot: interface 1x size

![Screenshot_1](https://github.com/Ehhthan/HappyHud-Issues/assets/99342964/4d53d193-f912-4a1c-82f8-450308b295c7)
![Screenshot_2](https://github.com/Ehhthan/HappyHud-Issues/assets/99342964/b082515b-173a-4ed7-a4d9-d98d3c8a16e8)

**Comment by Ehhthan** [comment]
You need to make sure that your positioning is configured correctly. Can you post the config here?

**Comment by distribate** [comment]
> You need to make sure that your positioning is configured correctly. Can you post the config here?

Yep

Asset: https://pastebin.com/VKfSTDy6
Layout: https://pastebin.com/cafmFk99

**Comment by distribate** [comment]
Deal with problems... thk!
