### ISSUE TITLE
horse and montures all

### ISSUE THREAD

**Issue by dinobossytnew** [Ehhthan/HappyHud-Issues#67]
There is no listener of the horse's mount, its life or speed, nor of other pets.

**Comment by dinobossytnew** [comment]
many designers' huds are affected by this lack of functionality in 1 hud as people.

**Comment by Bimic332** [comment]
![image](https://github.com/Ehhthan/HappyHud-Issues/assets/88329328/153f77b4-aea2-49b6-bc09-892c3d7686e8)

**Comment by dinobossytnew** [comment]
![descarga](https://github.com/Ehhthan/HappyHud-Issues/assets/58078116/364651ff-73fe-4640-8027-fe79fa2ea628)
![2023-05-24_19 10 09](https://github.com/Ehhthan/HappyHud-Issues/assets/58078116/61836278-e5aa-41e8-8ed5-5f8ba7fa41fc)

**Comment by dinobossytnew** [comment]
noting horse bar
🗡️

**Comment by dinobossytnew** [comment]
use and add wiki info?

**Comment by dinobossytnew** [comment]
?
