### ISSUE TITLE
Depending on the Minecraft window size, HUD is not visible.

### ISSUE THREAD

**Issue by paiow** [Ehhthan/HappyHud-Issues#73]
https://github.com/Ehhthan/HappyHud-Issues/assets/113721459/edaf2b1b-1f2e-41c3-b3da-7b0b2acaa3ef

You can't see the HUD when it's the normal window size, but you can see the HUD if you stretch the window down a little.

Version 1.0.5 Release.

**Comment by Ehhthan** [comment]
Your boss bar hud-position is set to 5. This makes it so it will not display please set it to this.
```
boss-bar:
  hud-position: 4
  color: yellow
  ```
