### ISSUE TITLE
Unhandled exception occured in onPacketSending

### ISSUE THREAD

**Issue by Complex1t** [Ehhthan/HappyHud-Issues#78]
Hello,

Several times a day, I get a bunch of errors from HappyHUD. I'm not sure of the exact way to replicate it, but from the stacktrace it seems like it doesn't like dealing with Jobs/mcMMO boss bars. Sometimes I get reports from players saying their boss bar is stuck (as in it's just always there and doesn't update), maybe this has something to do with it?

Log: https://pastebin.com/1cV6fruw

**Comment by Ehhthan** [comment]
Hopefully fixed in latest version.
