### ISSUE TITLE
Add option to scale icon

### ISSUE THREAD

**Issue by Boy0000** [Ehhthan/HappyHud-Issues#8]
Sometimes the image you wanna use is too big or too small. Would be nice for icon to have scaling property like normal fonts let you do for unicodes

![image](https://user-images.githubusercontent.com/62521371/186977578-703bd9cf-e969-42e9-8e5f-e3bd2e0e85b3.png)

**Comment by jacquelynra** [comment]
Exactly. Scaling inside Minecraft also has the benefit that it shows HD if you change GUI Scales.

**Comment by Boy0000** [comment]
Seeing as this now works as it should for unicodes in the text field, this would be a great addition
Currently cant move the icons in any good way as theyre only able to be in text if you need rescale it

**Comment by Ehhthan** [comment]
agreed, now that i have a working width formula for scales i can see what i can do

**Comment by Ehhthan** [comment]
Added in 0.2.4-SNAPSHOT. (finally)
