### ISSUE TITLE
[Bug] Players get kicked if you have 4+ bossbars active and at least one of them are removed

### ISSUE THREAD

**Issue by Complex1t** [Ehhthan/HappyHud-Issues#80]
Players get kicked if they have 4 or more boss bars, and at least one of them is removed.

Here is a demonstration video:
https://i.imgur.com/DDKHPy6.mp4

In the above video, I am using AnnouncerPlus to give myself a boss bar that is draining over 5 seconds. It should be noted that it does not matter where the boss bar is from (vanilla mobs, MythicMobs, plugins, etc... all result in this issue)

**Comment by Ehhthan** [comment]
Should be fixed in 1.0.8-RELEASE.
