### ISSUE TITLE
ActionBar support

### ISSUE THREAD

**Issue by ladakx** [Ehhthan/HappyHud-Issues#87]
Currently the plugin only supports displaying hud in the BossBar, which can cause some issues when resizing the screen. (HUD that should be displayed at the very bottom of the screen (near the hotbar) may shift if you resize the screen).

I suggest to introduce an option that will determine where to display layout. in action-bar or bossbar.

Displaying the layout Action-bar makes it possible to fix this problem. Since Minecraft displays text in the ActionBar "relative" to the hotbar

This is also the case with Title and subtitle.
Title and subtitle can display text relative to the center of the screen.

exampleLayout:
    showLayout: Boss_Bar/Action_Bar/Title/Subtitle

**Comment by Ehhthan** [comment]
The issues that you are having with the boss bar should all be resolved in the latest versions. The boss bar is already relative in the same way the action bar is so there's no reason to add functionality for this.
