### ISSUE TITLE
Ability to choose where to place textures, fonts, and other resourcepack assemblies.

### ISSUE THREAD

**Issue by ladakx** [Ehhthan/HappyHud-Issues#88]
Ability to choose where to place textures, fonts, and other resourcepack assemblies.

Currently, the happyhud resourcepack loads all assemblies into assets/happyhud. I propose to make this customizable so that users can put asset files in assets/minecraft. or in assets/ui or in assets/server_name for example

Each user or server has its own resourcepack architecture. I think it's a good idea to be able to stick to it.

**Comment by Ehhthan** [comment]
HappyHud needs to use it's own namespace so that other assets or plugins do not interfere.
