### ISSUE TITLE
Hud is not displayed

### ISSUE THREAD

**Issue by RafY-log** [Ehhthan/HappyHud-Issues#9]
![2022-08-27_05 25 00](https://user-images.githubusercontent.com/42149890/186986750-8df50304-f7a2-43aa-ae50-ee38e15c15b3.png)
![886ecd0ee4e4c7296cc3dcc86c966af2](https://user-images.githubusercontent.com/42149890/186986833-5101f6bc-5cd4-4e73-a845-70b218ffd574.png)

Server: paper-1.19-81
Java 18
client: 1.19-OptiFine_HD_U_H9
Lang: JP
windows11

**Comment by RafY-log** [comment]
https://timings.aikar.co/dev/?id=2fd25052fe5f4b2689b1af5f7cbf1f99#timings
![7f7761402883375e30cf49e65037cca6](https://user-images.githubusercontent.com/42149890/187044975-df0935f4-6860-46ac-b31b-ed18da62c7ed.png)
![f6584e0422e3e40c5ec0a85392cec2e9](https://user-images.githubusercontent.com/42149890/187044978-c882dc1b-4113-4e5c-8613-9944feeedaf8.png)
![1fb21524663bc40d7d613465045f77a8](https://user-images.githubusercontent.com/42149890/187044984-70b03fe7-eee7-419d-b57c-f538fccc9158.png)

**Comment by Ehhthan** [comment]
Update your paper.

**Comment by RafY-log** [comment]
The latest 1.19 version of paperMC is 1.19-81. Are you saying I should update to 1.19.1?

**Comment by Ehhthan** [comment]
I've heard reports that paper is bugged at 1.19

**Comment by Ehhthan** [comment]
Can you confirm that paper is the issue?

**Comment by RafY-log** [comment]
It was caused by PAPER, I updated to 1.19.1 and it showed up
![2022-08-28_18 42 01](https://user-images.githubusercontent.com/42149890/187067916-f08710a2-e2e0-4233-b297-e1d4315bf4e8.png)
.

**Comment by RafY-log** [comment]
I tried it and spigot-1.19 doesn't show Hud as well as PaperMC
I can't say that PaperMC is the cause.

**Comment by Ehhthan** [comment]
The problem is how how the core shader works on 1.19.0 specifically. Mojang added the drop shadow in a later version and shifted things around. You can use the new compatibility-mode in the config.yml (regenerate if you don't have it) to force the bars to appear on all versions.
