### ISSUE TITLE
boss bar always displayed.

### ISSUE THREAD

**Issue by ALPHABLANC1** [Ehhthan/HappyHud-Issues#91]
![123123123123](https://github.com/Ehhthan/HappyHud-Issues/assets/152409734/c9b5ebce-a2cc-4055-9159-55ff243f5979)

The boss bar persists even if you remove the layout, as shown in the picture above. Can I know how to get rid of it?

**Comment by roberth11234** [comment]
Have the same problem. How u solved it?
