### ISSUE TITLE
yellow boss bars

### ISSUE THREAD

**Issue by roberth11234** [Ehhthan/HappyHud-Issues#94]
![image](https://github.com/Ehhthan/HappyHud-Issues/assets/154921097/ab6947f8-3d5d-428f-993a-f4c761ab0be2)
I see these boss bars constantly, I can't get rid of them

**Comment by Ehhthan** [comment]
You are not merging your resource pack correctly.

**Comment by roberth11234** [comment]
I dont even put a resourcepack, I test with / without. With default files I have this problem
