### ISSUE TITLE
huge memory leak due to happyhud

### ISSUE THREAD

**Issue by Ecilpse** [Ehhthan/HappyHud-Issues#97]
server crashed due to Java heap space, so i make heap dump and find what is cause by Eclipse MemoryAnalyzer.
result is this:
server A
![image](https://github.com/Ehhthan/HappyHud-Issues/assets/25452835/d845cec0-6122-46d8-acc9-6add4e4643c2)

server B
![스크린샷 2024-01-15 025658](https://github.com/Ehhthan/HappyHud-Issues/assets/25452835/c941b0b9-4aab-4063-9cff-87cedb3c2545)

I think the memory leak occured by Happyhud is ridiculously high, can it check?

**Comment by Ehhthan** [comment]
Should be solved in latest version.
