### ISSUE TITLE
Standard hearts and other parts are not removed

### ISSUE THREAD

**Issue by Kirigaiyo** [Ehhthan/HappyHud-Issues#98]
I'm getting it now, but it used to be fine and I didn't change anything.

![297120305-ceb25a25-1930-4b3f-997a-9af13a6ebc64](https://github.com/Ehhthan/HappyHud-Issues/assets/94529024/06ae7054-2ecd-4e12-b7d6-6730abd815e8)

**Comment by Ehhthan** [comment]
Not a feature of happyhud. If you want to remove default textures, you need to do it yourself in your resource pack.
