### ISSUE TITLE
Memory LEAK

### ISSUE THREAD

**Issue by dinobossytnew** [Ehhthan/HappyHud-Issues#99]
spark info: https://spark.lucko.me/YNigq6XPyH in real time
![image](https://github.com/Ehhthan/HappyHud-Issues/assets/58078116/69512670-4b6f-4908-b3a8-271e6ad8ca7f)

**Comment by dinobossytnew** [comment]
https://spark.lucko.me/LFqtP5PSAF in stoped

**Comment by Ehhthan** [comment]
This does not look like a memory leak. I notice what is taking up the most resources is the JavascriptPlaceholderExpansion. You've probably got some rogue code that is not working correctly.

**Comment by dinobossytnew** [comment]
> This does not look like a memory leak. I notice what is taking up the most resources is the JavascriptPlaceholderExpansion. You've probably got some rogue code that is not working correctly.

the setup for happyhud?
